== Accounts

An API user account and password is required to access the UpCloud API.
The API user is associated with an UpCloud account.
A use account may have multiple API users to be used in different client software.
In order to use resources from the cloud, the account must have enough credits.

=== Credits

Credits are used to pay cloud resources such as servers, storages, network traffic and IP addresses.
Credits are automatically deducted for used resources on an hourly basis.
Should the user run out of credits, active resources will be disabled and reactivated after the credit balance returns to positive.
Credits can be purchased from the UpCloud website.

=== Get account information

Returns information on the user's account.

[source,HTTP]
----
GET /1.2/account HTTP/1.1
Host: api.upcloud.com
Accept: application/json; charset=UTF-8
----

[source,HTTP]
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

[source,JSON]
{
  "account": {
    "credits": "10000",
    "username": "username"
  }
}

[source,groovy,subs="+attributes"]
----
@Grab("fi.linuxbox:groovy-upcloud-script:{project-version}")
import fi.linuxbox.upcloud.script.*

def upCloud = new UpCloudContext(this.args).upCloud

upCloud.account { resp ->
    resp.META.status == 200
    def account = resp.account

    account.class.simpleName == 'Account'
    account.credits == '10000'
    account.username == 'username'
}
----

A successful response will contain a property called `account` whose type is `Account`.
